In [1]:
# df.loc[1:2,'语文']

#### （一）创建DataFrame对象，并针对此对象，完成下面的操作：
1.	输出x列的数据。
2.	输出前两行数据。
3.	输出x列和z列的数据。
4.	输出前两列数据。
5.	输出后两行数据。
6.	输出第1行和第3行数据。

In [2]:
import pandas as pd
df = pd.DataFrame({'x': [1.0, 2.0, 3.0], 
                   'y':[1, 2, 3],
                   'z': ['a','b','c']})
df

     x  y  z
0  1.0  1  a
1  2.0  2  b
2  3.0  3  c

In [8]:
# 1.
df['x']

0    1.0
1    2.0
2    3.0
Name: x, dtype: float64

In [6]:
# 2.
df.iloc[0:2]

     x  y  z
0  1.0  1  a
1  2.0  2  b

In [7]:
# 3.
df[['x','z']]

     x  z
0  1.0  a
1  2.0  b
2  3.0  c

In [9]:
# 4.
df.iloc[:,0:2]

     x  y
0  1.0  1
1  2.0  2
2  3.0  3

In [10]:
# 5.
df.tail(2)

     x  y  z
1  2.0  2  b
2  3.0  3  c

In [16]:
# 6.
df.iloc[[0,2]]

     x  y  z
0  1.0  1  a
2  3.0  3  c

#### （二）根据素材文件data_sheet.xlsx，完成下面的操作：
1.	读取此Excel文件中名为CSoft的工作表数据，这是取自中国软件从2012年12月至2020年6月的资产负债表的相关数据。
2.	通过 usecols 参数导入中国软件的资产合计列数据。
3.	通过 nrows 参数导入中国软件2020年的所有数据。
4.	将（3）的查询结果存入一个新的Excel文件中，文件名为data_sheet1.xlsx。

In [22]:
# 1.
CSoftDF=pd.read_excel('data_sheet.xlsx',sheet_name='CSoft')  # 读取Excel文件CSoft工作表
CSoftDF  # 显示对象

           年份          资产合计          负债合计  所有者权益（或股东权益)合计  负债和所有者权益（或股东权益)总计
0  2020-06-30  5.557406e+09  3.346629e+09    2.210777e+09       5.557406e+09
1  2020-03-31  5.851825e+09  3.358423e+09    2.493402e+09       5.851825e+09
2  2019-12-31  6.743722e+09  3.981950e+09    2.761773e+09       6.743722e+09
3  2019-09-30  5.500004e+09  3.219073e+09    2.280931e+09       5.500004e+09
4  2019-06-30  5.509150e+09  3.185099e+09    2.324051e+09       5.509150e+09
5  2019-03-31  5.619935e+09  3.160419e+09    2.459516e+09       5.619935e+09
6  2018-12-31  5.710849e+09  3.105448e+09    2.605402e+09       5.710849e+09
7  2018-09-30  4.712688e+09  2.544376e+09    2.168312e+09       4.712688e+09
8  2018-06-30  4.610415e+09  2.409854e+09    2.200561e+09       4.610415e+09
9  2018-03-31  4.704466e+09  2.331712e+09    2.372754e+09       4.704466e+09
10 2017-12-31  5.271271e+09  2.747742e+09    2.523530e+09       5.271271e+09
11 2017-09-30  5.303051e+09  2.786341e+09    2.516710e+09       5.303051e+09
12 2017-06-30  5.730134e+09  3.107095e+09    2.623038e+09       5.730134e+09
13 2017-03-31  5.481715e+09  2.736312e+09    2.745403e+09       5.481715e+09
14 2016-12-31  5.967907e+09  3.059595e+09    2.908311e+09       5.967907e+09
15 2016-09-30  5.345118e+09  2.753279e+09    2.591840e+09       5.345118e+09
16 2016-06-30  4.934458e+09  2.226965e+09    2.707493e+09       4.934458e+09
17 2016-03-31  4.998240e+09  2.258899e+09    2.739340e+09       4.998240e+09
18 2015-12-31  5.523026e+09  2.709547e+09    2.813478e+09       5.523026e+09
19 2015-09-30  3.967280e+09  1.824596e+09    2.142684e+09       3.967280e+09
20 2015-06-30  4.071525e+09  1.864262e+09    2.207263e+09       4.071525e+09
21 2015-03-31  4.024881e+09  1.787532e+09    2.237349e+09       4.024881e+09
22 2014-12-31  4.427302e+09  2.103106e+09    2.324196e+09       4.427302e+09
23 2014-09-30  3.988614e+09  1.835554e+09    2.153059e+09       3.988614e+09
24 2014-03-31  4.060087e+09  1.810480e+09    2.249606e+09       4.060087e+09
25 2014-03-31  4.060087e+09  1.810480e+09    2.249606e+09       4.060087e+09
26 2013-12-31  4.521597e+09  2.214031e+09    2.307565e+09       4.521597e+09
27 2013-09-30  3.609310e+09  2.019482e+09    1.589828e+09       3.609310e+09
28 2013-06-30  3.582634e+09  1.989054e+09    1.593580e+09       3.582634e+09
29 2013-03-31  3.180388e+09  1.555417e+09    1.624971e+09       3.180388e+09
30 2012-12-31  3.490330e+09  1.840326e+09    1.650004e+09       3.490330e+09

In [25]:
# 2.
# 读取Excel文件CSoft工作表的数据，导入中国软件的“资产合计”列
CSoftDF=pd.read_excel('data_sheet.xlsx',sheet_name='CSoft',usecols='B') 
CSoftDF

            资产合计
0   5.557406e+09
1   5.851825e+09
2   6.743722e+09
3   5.500004e+09
4   5.509150e+09
5   5.619935e+09
6   5.710849e+09
7   4.712688e+09
8   4.610415e+09
9   4.704466e+09
10  5.271271e+09
11  5.303051e+09
12  5.730134e+09
13  5.481715e+09
14  5.967907e+09
15  5.345118e+09
16  4.934458e+09
17  4.998240e+09
18  5.523026e+09
19  3.967280e+09
20  4.071525e+09
21  4.024881e+09
22  4.427302e+09
23  3.988614e+09
24  4.060087e+09
25  4.060087e+09
26  4.521597e+09
27  3.609310e+09
28  3.582634e+09
29  3.180388e+09
30  3.490330e+09

In [26]:
# 3.
# 通过 nrows参数导入指定的行
# 读取Excel文件CSoft工作表，导入中国软件前两行的数据
import pandas as pd
CSoftDF=pd.read_excel('data_sheet.xlsx',sheet_name='CSoft',nrows=2)  
CSoftDF

          年份          资产合计          负债合计  所有者权益（或股东权益)合计  负债和所有者权益（或股东权益)总计
0 2020-06-30  5.557406e+09  3.346629e+09    2.210777e+09       5.557406e+09
1 2020-03-31  5.851825e+09  3.358423e+09    2.493402e+09       5.851825e+09

In [28]:
# 4.
CSoftDF.to_excel('data_sheet1.xlsx',index=False)   # 将数据存入Excel文件

#### （三）中国软件-600536-季报数据.xlsx文件的“利润表”保存了中国软件从2012年12月到2020年6月的全部利润表季报数据。请根据此数据完成下面的操作。
1.	读入此文件中名为 “利润表”的工作表数据。
2.	查询利润表的营业总收入项及明细项数据。
3.	采用head()函数获取利润表的前9行数据。
4.	查询利润表的“一、营业总收入”“二、营业总成本”数据。

In [35]:
# 1.
import pandas as pd    # 导入pandas包
# 读取中国软件季报数据
df=pd.read_excel("中国软件-600536-季报数据.xlsx",sheet_name='利润表',index_col=0)
df

,REPORTDATE,2020/6/30 0:00:00,2020/3/31 0:00:00,2019/12/31 0:00:00,2019/9/30 0:00:00,2019/6/30 0:00:00,2019/3/31 0:00:00,2018/12/31 0:00:00,2018/9/30 0:00:00,2018/6/30 0:00:00,...,2015/3/31 0:00:00,2014/12/31 0:00:00,2014/9/30 0:00:00,2014/3/31 0:00:00,2014/3/31 0:00:00.1,2013/12/31 0:00:00,2013/9/30 0:00:00,2013/6/30 0:00:00,2013/3/31 0:00:00,2012/12/31 0:00:00
利润表,,,,,,,,,,,,,,,,,,,,,
一、营业总收入,TOTALOPERATEREVE,1.393577e+09,6.021164e+08,5.819592e+09,3.145931e+09,2.065023e+09,1.007083e+09,4.613161e+09,2.541016e+09,1.530669e+09,...,4.779116e+08,3.232502e+09,1.906682e+09,5.618474e+08,5.618474e+08,2.980643e+09,1.702072e+09,1.143908e+09,5.163128e+08,2.680567e+09
其中：营业收入,OPERATEREVE,1.393577e+09,6.021164e+08,5.819592e+09,3.145931e+09,2.065023e+09,1.007083e+09,4.613161e+09,2.541016e+09,1.530669e+09,...,4.779116e+08,3.232502e+09,1.906682e+09,5.618474e+08,5.618474e+08,2.980643e+09,1.702072e+09,1.143908e+09,5.163128e+08,2.680567e+09
利息收入*,INTREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
已赚保费*,PREMIUMEARNED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
手续费及佣金收入*,COMMREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
（一）归属于母公司所有者的综合收益总额,PARENTCINCOME,-4.093187e+08,-1.614654e+08,6.441977e+07,-2.452880e+08,-2.089278e+08,-1.009409e+08,1.189926e+08,-2.358851e+08,-2.228690e+08,...,-5.388969e+07,3.481379e+07,-1.029705e+08,-4.456711e+07,-4.456711e+07,7.841476e+06,-4.619244e+07,-3.900809e+07,-1.720104e+07,-1.910891e+07
（二）归属于少数股东的综合收益总额,MINORITYCINCOME,-8.142979e+07,-3.759861e+07,7.992993e+07,-3.351383e+07,-2.780404e+07,-2.376839e+07,1.099328e+07,-9.082768e+07,-7.186339e+07,...,-2.255611e+07,1.459354e+07,-2.699079e+07,-1.334732e+07,-1.334732e+07,4.307640e+07,1.093704e+07,1.869176e+06,-4.959188e+05,3.478860e+07
八、每股收益,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
（一）基本每股收益,BASICEPS,-8.300000e-01,-3.300000e-01,1.300000e-01,-5.000000e-01,-4.200000e-01,-2.100000e-01,2.400000e-01,-4.800000e-01,-4.500000e-01,...,-1.100000e-01,7.000000e-02,-2.100000e-01,-9.000000e-02,-9.000000e-02,1.300000e-01,1.300000e-02,3.000000e-02,7.000000e-03,2.600000e-01
（二）稀释每股收益,DILUTEDEPS,-8.300000e-01,-3.300000e-01,1.300000e-01,-5.000000e-01,-4.200000e-01,-2.100000e-01,2.400000e-01,-4.800000e-01,-4.500000e-01,...,-1.100000e-01,7.000000e-02,-2.100000e-01,-9.000000e-02,-9.000000e-02,1.300000e-01,1.300000e-02,3.000000e-02,7.000000e-03,2.600000e-01

In [41]:
# 2.
df.iloc[0:9,]

,REPORTDATE,2020/6/30 0:00:00,2020/3/31 0:00:00,2019/12/31 0:00:00,2019/9/30 0:00:00,2019/6/30 0:00:00,2019/3/31 0:00:00,2018/12/31 0:00:00,2018/9/30 0:00:00,2018/6/30 0:00:00,...,2015/3/31 0:00:00,2014/12/31 0:00:00,2014/9/30 0:00:00,2014/3/31 0:00:00,2014/3/31 0:00:00.1,2013/12/31 0:00:00,2013/9/30 0:00:00,2013/6/30 0:00:00,2013/3/31 0:00:00,2012/12/31 0:00:00
利润表,,,,,,,,,,,,,,,,,,,,,
一、营业总收入,TOTALOPERATEREVE,1.393577e+09,602116408.1,5.819592e+09,3.145931e+09,2.065023e+09,1.007083e+09,4.613161e+09,2.541016e+09,1.530669e+09,...,4.779116e+08,3.232502e+09,1.906682e+09,5.618474e+08,5.618474e+08,2.980643e+09,1.702072e+09,1.143908e+09,5.163128e+08,2.680567e+09
其中：营业收入,OPERATEREVE,1.393577e+09,602116408.1,5.819592e+09,3.145931e+09,2.065023e+09,1.007083e+09,4.613161e+09,2.541016e+09,1.530669e+09,...,4.779116e+08,3.232502e+09,1.906682e+09,5.618474e+08,5.618474e+08,2.980643e+09,1.702072e+09,1.143908e+09,5.163128e+08,2.680567e+09
利息收入*,INTREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
已赚保费*,PREMIUMEARNED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
手续费及佣金收入*,COMMREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
银行业务利息净收入,BANKINTNREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
非保险业务手续费及佣金净收入,NINSURCOMMNREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
非保险业务手续费及佣金收入,NINSURCOMMREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
非保险业务手续费及佣金支出,NINSURCOMMEXP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
# 3.
df.head(9)

,REPORTDATE,2020/6/30 0:00:00,2020/3/31 0:00:00,2019/12/31 0:00:00,2019/9/30 0:00:00,2019/6/30 0:00:00,2019/3/31 0:00:00,2018/12/31 0:00:00,2018/9/30 0:00:00,2018/6/30 0:00:00,...,2015/3/31 0:00:00,2014/12/31 0:00:00,2014/9/30 0:00:00,2014/3/31 0:00:00,2014/3/31 0:00:00.1,2013/12/31 0:00:00,2013/9/30 0:00:00,2013/6/30 0:00:00,2013/3/31 0:00:00,2012/12/31 0:00:00
利润表,,,,,,,,,,,,,,,,,,,,,
一、营业总收入,TOTALOPERATEREVE,1.393577e+09,602116408.1,5.819592e+09,3.145931e+09,2.065023e+09,1.007083e+09,4.613161e+09,2.541016e+09,1.530669e+09,...,4.779116e+08,3.232502e+09,1.906682e+09,5.618474e+08,5.618474e+08,2.980643e+09,1.702072e+09,1.143908e+09,5.163128e+08,2.680567e+09
其中：营业收入,OPERATEREVE,1.393577e+09,602116408.1,5.819592e+09,3.145931e+09,2.065023e+09,1.007083e+09,4.613161e+09,2.541016e+09,1.530669e+09,...,4.779116e+08,3.232502e+09,1.906682e+09,5.618474e+08,5.618474e+08,2.980643e+09,1.702072e+09,1.143908e+09,5.163128e+08,2.680567e+09
利息收入*,INTREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
已赚保费*,PREMIUMEARNED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
手续费及佣金收入*,COMMREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
银行业务利息净收入,BANKINTNREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
非保险业务手续费及佣金净收入,NINSURCOMMNREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
非保险业务手续费及佣金收入,NINSURCOMMREVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
非保险业务手续费及佣金支出,NINSURCOMMEXP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
# 4.
df.loc[['一、营业总收入','二、营业总成本'],:]

,REPORTDATE,2020/6/30 0:00:00,2020/3/31 0:00:00,2019/12/31 0:00:00,2019/9/30 0:00:00,2019/6/30 0:00:00,2019/3/31 0:00:00,2018/12/31 0:00:00,2018/9/30 0:00:00,2018/6/30 0:00:00,...,2015/3/31 0:00:00,2014/12/31 0:00:00,2014/9/30 0:00:00,2014/3/31 0:00:00,2014/3/31 0:00:00.1,2013/12/31 0:00:00,2013/9/30 0:00:00,2013/6/30 0:00:00,2013/3/31 0:00:00,2012/12/31 0:00:00
利润表,,,,,,,,,,,,,,,,,,,,,
一、营业总收入,TOTALOPERATEREVE,1.393577e+09,6.021164e+08,5.819592e+09,3.145931e+09,2.065023e+09,1.007083e+09,4.613161e+09,2.541016e+09,1.530669e+09,...,4.779116e+08,3.232502e+09,1.906682e+09,5.618474e+08,5.618474e+08,2.980643e+09,1.702072e+09,1.143908e+09,5.163128e+08,2.680567e+09
二、营业总成本,TOTALOPERATEEXP,1.878101e+09,8.115123e+08,5.720036e+09,3.453921e+09,2.292037e+09,1.125936e+09,4.523317e+09,2.857463e+09,1.804278e+09,...,6.126713e+08,3.316427e+09,2.127256e+09,6.497513e+08,6.497513e+08,3.065458e+09,1.843418e+09,1.262478e+09,5.832793e+08,3.040235e+09